FROM php:8.3-fpm

ENV COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/composer

COPY --from=composer:2.8.6 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    git unzip libzip-dev libicu-dev libonig-dev iputils-ping && \
    apt-get install -y sqlite3 libsqlite3-dev && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-install intl pdo_mysql zip bcmath pdo_sqlite

COPY ./php.ini /usr/local/etc/php/php.ini

WORKDIR /data

RUN touch /data/sqlite.db && \
    chown www-data:www-data /data/sqlite.db && \
    chmod 664 /data/sqlite.db
