services: 
  app:
    build:
      context: .
      dockerfile: infra/php/Dockerfile.test
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  composer:
    image: composer:2
    volumes:
      - ./src:/var/www/html
    command: install --no-interaction --optimize-autoloader

  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store:
