services:
  app:
    build: ./infra/php
    depends_on:
      - db
    command: sh -c "php artisan migrate && php-fpm"
    volumes:
      - ./src:/var/www/html
      - ./src/public/build:/var/www/html/public/build
    working_dir: /var/www/html


  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store: