services: 
  app:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
     - ./src:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "php artisan package:discover --ansi &&
             php-fpm"

  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store:
