services:
  app:
    build:
      context: ./infra/php
      dockerfile: Dockerfile.test

    command: sh -c "cp .env.example .env && \
                apt-get update && \
                apt-get install -y curl libgd-dev libjpeg-dev libpng-dev libfreetype6-dev pkg-config wget gnupg2 && \
                wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list && \
                apt-get update && \
                apt-get install -y google-chrome-stable && \
                curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
                apt-get install -y nodejs && \
                npm install -g npm@11.3.0 && \
                docker-php-ext-configure gd --with-freetype --with-jpeg && \
                docker-php-ext-install gd && \
                composer install --dev --optimize-autoloader && \
                php artisan key:generate --force && \
                npm install && \
                npm run build && \
                php artisan migrate --force && \
                php-fpm"

    volumes:
      - ./src:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
      - public_build_data:/var/www/html/public/build

    working_dir: /var/www/html

  web:
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

volumes:
 vendor_data:
 node_modules_data:
 public_build_data:

