services:
  app:
    build:
      context: ./infra/php
      dockerfile: Dockerfile.test
    # Dockerfile.test内の command では初期化処理（.envのコピー、composer install 等）は含まず、
    # ここでは必要なパッケージのインストール後、ただ php-fpm が起動するのみ。
    command: >
      sh -c "apt-get update &&
      apt-get install -y libgd-dev libjpeg-dev libpng-dev libfreetype6-dev pkg-config &&
      docker-php-ext-configure gd --with-freetype --with-jpeg &&
      docker-php-ext-install gd &&
      exec php-fpm"
    volumes:
      - ./src:/var/www/html
      - vendor_data:/var/www/html/vendor
    working_dir: /var/www/html

  web:
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

volumes:
  vendor_data:
