services:
  app:
    build: ./infra/php
    depends_on:
      - db

    command: sh -c "apt-get update && \
             apt-get install -y libgd-dev libjpeg-dev libpng-dev libfreetype6-dev pkg-config && \
             docker-php-ext-configure gd --with-freetype --with-jpeg && \
             docker-php-ext-install gd && \
             composer install --dev --optimize-autoloader && \
             php artisan migrate --force && \
             php-fpm"


    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html


  web:
    image: nginx:1.20-alpine
    # ports:
    #   - 8080:80
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store: