name: CI/CD Pipeline

permissions:
  contents: read
  packages: write     
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FOR_GHCR }}  

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infra/php/Dockerfile.prod
          push: true
          no-cache: true
          tags: ghcr.io/141takahiro/micelle-app:${{ github.sha }}


  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |

            echo "${{ secrets.FOR_GHCR }}" | docker login ghcr.io -u 141Takahiro --password-stdin

            if grep -q '"ghcr.io"' ~/.docker/config.json; then
            echo "GHCR login successful."
            else
              echo "GHCR login failed." && exit 1
            fi

            cd ~/micelle
            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            docker-compose -f docker-compose.prod.yml down -v
            docker system prune -a -f

            export TAG=$(git rev-parse HEAD)
            echo "TAG is ${TAG}"

            docker-compose -f docker-compose.prod.yml pull
            docker images

            docker-compose -f docker-compose.prod.yml up -d --remove-orphans