name: Lighthouse Tests
on:
  workflow_dispatch:

jobs:
  lighthouse-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and start Docker containers
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Wait for server to start
        run: sleep 300

      - name: Get logs for micelle-app-1
        run: docker logs micelle-app-1

      - name: Start server inside container
        run: docker exec -it micelle-app-1 bash -c "npm start"
        
      - name: Wait for server to start
        run: sleep 100

      - name: Run Lighthouse CI
        run: npx lhci autorun --chrome-flags="--headless=false"
        working-directory: src
